name: Deploy React Build to BlogFrontStage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.name "Kenji Ozawa"
          git config --global user.email "keoz002@ess.ais.ac.nz"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Clone target repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@github.com/kozawanz/BlogFrontStage.git target-repo

      - name: Sync build folder to target repo
        run: |
          rsync -av --exclude='.git' --delete ./build/ target-repo/
          cd target-repo
          git add .
          git commit -m "🚀 Auto-deploy build folder from private repo ($(date +'%Y-%m-%d %H:%M'))" || echo "No changes to commit"
          git push origin main
